### ISSUE TITLE
Upgrade?

### ISSUE THREAD

**Issue by ghost** [matklad/fish-config#1]
Hi @matklad  
I'm no longer maintaining omf, and would appreciate a ton if you can upgrade to [fisherman](https://github.com/fisherman/fisherman):
- Why? fisherman/fisherman#69 (comment)

Everything, including legacy plugins/themes work great with fisherman, but new content is no longer compat. with oh-my-fish.

And if you need help with anything, I'm just a ping away :)

**Comment by matklad** [comment]
Wow, thanks a lot!

The thing is, I've switched from fish to zsh when I've found [zsh autosuggestions](https://github.com/zsh-users/zsh-autosuggestions). I'll certainly check out the fisherman if I try fish again.

**Comment by ghost** [comment]
Gotcha. Do check it out. If you need help setting anything up I'd be glad to help with anything! Cheers.
